version: "3.8"
services:

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - global-network

  db:
    image: postgres
    container_name: customer_service_db
    environment:
      POSTGRES_USER: ravil
      POSTGRES_PASSWORD: ravil
      POSTGRES_DB: customer_service_database
    ports:
      - "5432:5432"
    networks:
      - global-network

  customer-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customer_service_app
    ports:
      - "8080:8080"
      - "8443:8443"
      - "5005:5005"
    depends_on:
      - db
      - zipkin
    networks:
      - global-network

networks:
  global-network:
    external: true