spring.application.name=customer-service

spring.datasource.url=jdbc:postgresql://db:5432/customer_service_database
spring.datasource.username=ravil
spring.datasource.password=ravil
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.enabled=false

logging.config=classpath:logback-spring.xml

management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.tracing.propagation.type=B3
