spring.application.name=customer-service

spring.datasource.url=jdbc:postgresql://db:5432/customer_service_database
spring.datasource.username=ravil
spring.datasource.password=ravil
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

logging.config=classpath:logback-spring.xml

management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.tracing.propagation.type=B3

server.port=8443

server.ssl.key-store=classpath:security/keystore.p12
server.ssl.key-store-password=ravila
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=customer-service
server.ssl.enabled=true
server.ssl.protocol=TLSv1.2

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

