# Specify the real driver class that P6Spy should use
realdriver=org.postgresql.Driver

# Log to standard output
appender=com.p6spy.engine.spy.appender.StdoutLogger

# Log format
logMessageFormat=com.p6spy.engine.spy.appender.MultiLineFormat

# Date format
dateformat=yyyy-MM-dd HH:mm:ss

# Optional: Specify the real driver class in a list
driverlist=org.postgresql.Driver
